apiVersion: v1
kind: Service
metadata:
  name: gitmir-lb-service
  namespace: gitmirdevtest
  labels:
    app: gitmir
spec:
  ports:
    - port: 80
  selector:
    app: gitmir
  type: LoadBalancer 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitmir-deployment
  namespace: gitmirdevtest
  labels:
    app: gitmir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitmir
  template:
    metadata:
      labels:
        app: gitmir
    spec:
      containers:
      - name: gitmir
        image: pksninjalabs/gitmir:0.10
        ports:
        - containerPort: 80
          name: gitmir-port
